### PR TITLE
Using gatsby-theme-blog from test repo

### PR DESCRIPTION
**Pull request by sachinmjadhav**
:no_entry_sign: DO NOT MERGE: Testing gatsby-theme-blog from a test repo. This will later be installed from npm if everything works fine.

### CODE REVIEW

**Comment by sanandnarayan** [comment]
@sachinmjadhav can you resolve the conflict?

**Comment by sanandnarayan** [comment]
There are issues with CSS hover on the READ POST button in blog listing page

**Comment by sachinmjadhav** [comment]
:no_entry_sign:  There are some CSS issues in the production mode but everything works fine in local. Please do not merge this PR until the issue is fixed.

**Comment by sachinmjadhav** [comment]
Final version can be found in PR https://github.com/Codebrahma/cbweb/pull/48. Closing this PR as it was causing some cache issue in Netlify deploy preview.

**Pull request closed without merging**
